name: Deploy development website

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-org-id: ${{ secrets.ZEIT_ORG_ID}}
          now-project-id: ${{ secrets.ZEIT_PROJECT_ID}} 
          working-directory: ./
